# Generated by Django 5.1.2 on 2024-11-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Common_Matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('age', 'Age'), ('gender', 'Gender'), ('weight', 'Weight'), ('height', 'Height'), ('religion', 'Religion'), ('caste', 'Caste'), ('income', 'Income'), ('profession', 'Profession'), ('education', 'Education'), ('marital_status', 'Marital Status'), ('language', 'Language'), ('location', 'Location')], max_length=20)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
