# Generated by Django 5.1.2 on 2024-11-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_maching_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common_matching',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
