# Generated by Django 5.1.2 on 2024-11-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_maching_app', '0002_alter_common_matching_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common_matching',
            name='type',
            field=models.CharField(choices=[('gender', 'Gender'), ('religion', 'Religion'), ('caste', 'Caste'), ('profession', 'Profession'), ('education', 'Education'), ('marital_status', 'Marital Status'), ('language', 'Language'), ('location', 'Location')], max_length=20),
        ),
    ]
