# Generated by Django 5.1.2 on 2024-10-24 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department_app', '0001_initial'),
        ('school_app', '0001_initial'),
        ('teacher_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department_task',
            name='department_HOD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teacher_app.teachers_task'),
        ),
        migrations.AddField(
            model_name='department_task',
            name='school_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school_app.school_task'),
        ),
    ]
