# Generated by Django 5.1.2 on 2024-10-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department_task',
            name='active_on',
            field=models.BooleanField(default=True),
        ),
    ]
