# Generated by Django 5.1.2 on 2024-10-29 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_app', '0005_alter_department_task_school_id'),
        ('teacher_app', '0008_alter_teachers_task_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department_task',
            name='department_HOD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teachers', to='teacher_app.teachers_task'),
        ),
    ]
