# Generated by Django 5.1.2 on 2024-10-30 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department_app', '0009_alter_department_task_department_hod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department_task',
            name='school_ID',
        ),
    ]
