# Generated by Django 5.1.2 on 2024-10-30 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_app', '0012_alter_department_task_department_hod'),
        ('teacher_app', '0011_remove_teachers_task_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department_task',
            name='department_HOD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='teacher_app.teachers_task'),
        ),
    ]
