# Generated by Django 5.1.2 on 2024-11-22 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcriptionTable',
            fields=[
                ('subcription_type', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('subcription_price', models.IntegerField(blank=True, null=True)),
                ('subcription_duration', models.IntegerField(blank=True, null=True)),
                ('subcription_active_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubcriptionForUser',
            fields=[
                ('subcription_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcription_price', models.IntegerField(blank=True, null=True)),
                ('subcription_duration', models.IntegerField(blank=True, null=True)),
                ('subcription_started_at', models.DateTimeField()),
                ('subcription_ending_at', models.DateTimeField()),
                ('subcription_active_status', models.BooleanField(default=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subcription_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcription_app.subcriptiontable')),
            ],
        ),
    ]
