# Generated by Django 5.1.2 on 2024-11-22 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcription_app', '0002_subcriptionsforuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubcriptionForUser',
        ),
    ]
