# Generated by Django 5.1.2 on 2024-11-06 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department_app', '__first__'),
        ('school_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers_Task',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('performance', models.FloatField(default=0.0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department_ID', models.ManyToManyField(blank=True, related_name='teachers', to='department_app.department_task')),
                ('school_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teachers', to='school_app.school_task')),
            ],
        ),
    ]
