# Generated by Django 5.1.2 on 2024-10-24 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department_app', '0001_initial'),
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers_Task',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('employee_id', models.AutoField(default=101, primary_key=True, serialize=False)),
                ('performance', models.FloatField(default=0.0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('department_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='department_app.department_task')),
                ('school_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school_app.school_task')),
            ],
        ),
    ]
