# Generated by Django 5.1.2 on 2024-10-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0004_alter_teachers_task_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers_task',
            name='employee_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
