# Generated by Django 5.1.2 on 2024-10-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0005_alter_teachers_task_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers_task',
            name='active_on',
            field=models.BooleanField(default=True),
        ),
    ]
