# Generated by Django 5.1.2 on 2024-10-28 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0006_teachers_task_active_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers_task',
            old_name='active_on',
            new_name='is_active',
        ),
    ]
