# Generated by Django 5.1.2 on 2024-10-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_app', '0010_remove_department_task_school_id'),
        ('teacher_app', '0010_alter_teachers_task_department_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers_task',
            name='department_ID',
        ),
        migrations.AddField(
            model_name='teachers_task',
            name='department_ID',
            field=models.ManyToManyField(blank=True, to='department_app.department_task'),
        ),
    ]
