# Generated by Django 5.1.2 on 2024-11-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_app', '0014_alter_department_task_department_hod'),
        ('teacher_app', '0012_remove_teachers_task_department_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers_task',
            name='department_ID',
        ),
        migrations.AddField(
            model_name='teachers_task',
            name='department_ID',
            field=models.ManyToManyField(blank=True, to='department_app.department_task'),
        ),
    ]
