# Generated by Django 5.1.2 on 2024-11-02 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0014_alter_teachers_task_department_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers_task',
            name='department_ID',
        ),
    ]
