# Generated by Django 5.1.2 on 2024-11-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_maching_app', '0001_initial'),
        ('preferance_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='age',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='caste',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='education',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='height',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='income',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='location',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='weight',
        ),
        migrations.AddField(
            model_name='preference',
            name='age',
            field=models.ManyToManyField(limit_choices_to={'type': 'age'}, related_name='user_preferences_age', to='common_maching_app.common_matching'),
        ),
        migrations.AddField(
            model_name='preference',
            name='caste',
            field=models.ManyToManyField(limit_choices_to={'type': 'caste'}, related_name='user_preferences_caste', to='common_maching_app.common_matching'),
        ),
        migrations.AddField(
            model_name='preference',
            name='education',
            field=models.ManyToManyField(limit_choices_to={'type': 'education'}, related_name='user_preferences_education', to='common_maching_app.common_matching'),
        ),
        migrations.AddField(
            model_name='preference',
            name='gender',
            field=models.ManyToManyField(limit_choices_to={'type': 'gender'}, related_name='user_preferences_gender', to='common_maching_app.common_matching'),
        ),
        migrations.AddField(
            model_name='preference',
            name='height',
            field=models.ManyToManyField(limit_choices_to={'type': 'height'}, related_name='user_preferences_height', to='common_maching_app.common_matching'),
        ),
        migrations.AddField(
            model_name='preference',
            name='income',
            field=models.ManyToManyField(limit_choices_to={'type': 'income'}, related_name='user_preferences_income', to='common_maching_app.common_matching'),
        ),
        migrations.AddField(
            model_name='preference',
            name='location',
            field=models.ManyToManyField(limit_choices_to={'type': 'location'}, related_name='user_preferences_location', to='common_maching_app.common_matching'),
        ),
        migrations.AddField(
            model_name='preference',
            name='profession',
            field=models.ManyToManyField(limit_choices_to={'type': 'profession'}, related_name='user_preferences_profession', to='common_maching_app.common_matching'),
        ),
        migrations.AddField(
            model_name='preference',
            name='religion',
            field=models.ManyToManyField(limit_choices_to={'type': 'religion'}, related_name='user_preferences_religion', to='common_maching_app.common_matching'),
        ),
        migrations.AddField(
            model_name='preference',
            name='weight',
            field=models.ManyToManyField(limit_choices_to={'type': 'weight'}, related_name='user_preferences_weight', to='common_maching_app.common_matching'),
        ),
    ]
