# Generated by Django 5.1.2 on 2024-11-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferance_app', '0002_remove_preference_age_remove_preference_caste_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='age',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='caste',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='education',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='height',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='income',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='location',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='weight',
        ),
        migrations.AddField(
            model_name='preference',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='caste',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
