# Generated by Django 5.1.2 on 2024-11-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferance_app', '0003_remove_preference_age_remove_preference_caste_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='age',
            new_name='age_from',
        ),
        migrations.RenameField(
            model_name='preference',
            old_name='height',
            new_name='height_from',
        ),
        migrations.RenameField(
            model_name='preference',
            old_name='weight',
            new_name='height_to',
        ),
        migrations.RenameField(
            model_name='preference',
            old_name='income',
            new_name='income_from',
        ),
        migrations.AddField(
            model_name='preference',
            name='age_to',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='income_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='weight_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='weight_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
