# Generated by Django 5.1.2 on 2024-11-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferance_app', '0005_remove_preference_age_from_remove_preference_age_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='caste',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='education',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='profession',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='religion',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
