# Generated by Django 5.1.2 on 2024-11-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferance_app', '0007_preference_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='langauge',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
