# Generated by Django 5.1.2 on 2024-11-18 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferance_app', '0008_preference_langauge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='langauge',
            new_name='language',
        ),
    ]
