# Generated by Django 5.1.2 on 2024-11-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='Teacher', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
