# Generated by Django 5.1.2 on 2024-11-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification_table',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='notification_table',
            name='notification_type',
            field=models.CharField(choices=[('reminder', 'Reminder'), ('new_message', 'New_Message'), ('new_match', 'New_Match'), ('offer', 'Offer'), ('profile', 'Profile'), ('preferance', 'Preferance'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('request', 'Request')], default='new_message', max_length=255),
        ),
    ]
