# Generated by Django 5.1.2 on 2024-11-20 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0003_notification_table_receiver_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification_table',
            name='receiver_id',
        ),
        migrations.RemoveField(
            model_name='notification_table',
            name='sender_id',
        ),
    ]
