# Generated by Django 5.1.2 on 2024-11-06 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department_app', '__first__'),
        ('school_app', '__first__'),
        ('teacher_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Task',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('roll_no', models.AutoField(primary_key=True, serialize=False)),
                ('total_marks_field', models.IntegerField(default=0)),
                ('percentage_field', models.FloatField(default=0.0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='department_app.department_task')),
                ('school_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='school_app.school_task')),
                ('teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teacher_app.teachers_task')),
            ],
        ),
    ]
