# Generated by Django 5.1.2 on 2024-10-24 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Task',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('roll_no', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('chemistry', models.IntegerField(default=0)),
                ('physics', models.IntegerField(default=0)),
                ('maths', models.IntegerField(default=0)),
                ('total_marks_field', models.IntegerField(default=0)),
                ('percentage_field', models.FloatField(default=0.0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teacher_app.teachers_task')),
            ],
        ),
    ]
