# Generated by Django 5.1.2 on 2024-10-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll_no', models.IntegerField(default=0)),
                ('chemistry', models.IntegerField(default=0)),
                ('physics', models.IntegerField(default=0)),
                ('maths', models.IntegerField(default=0)),
                ('total_marks', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('class_teacher', models.CharField(max_length=50)),
            ],
        ),
    ]
