# Generated by Django 5.1.2 on 2024-10-18 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_task',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='student_task',
            name='total_marks',
        ),
    ]
