# Generated by Django 5.1.2 on 2024-10-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_remove_student_task_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_task',
            name='id',
        ),
        migrations.AlterField(
            model_name='student_task',
            name='roll_no',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
