# Generated by Django 5.1.2 on 2024-10-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_remove_student_task_id_alter_student_task_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_task',
            name='percentage_field',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student_task',
            name='total_marks_field',
            field=models.IntegerField(default=0),
        ),
    ]
