# Generated by Django 5.1.2 on 2024-10-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_alter_student_task_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_task',
            name='roll_no',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
