# Generated by Django 5.1.2 on 2024-10-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_student_task_percentage_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Task',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('employee_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
    ]
