# Generated by Django 5.1.2 on 2024-10-22 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0005_teacher_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_task',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student_app.teacher_task'),
        ),
    ]
