# Generated by Django 5.1.2 on 2024-10-28 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_app', '0002_initial'),
        ('school_app', '0001_initial'),
        ('student_app', '0006_alter_student_task_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_task',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='department_app.department_task'),
        ),
        migrations.AddField(
            model_name='student_task',
            name='school_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school_app.school_task'),
        ),
    ]
