# Generated by Django 5.1.2 on 2024-10-22 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0006_student_task_teacher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_task',
            name='class_teacher',
        ),
    ]
