# Generated by Django 5.1.2 on 2024-10-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0007_remove_student_task_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_task',
            name='perfomance',
            field=models.FloatField(default=0.0),
        ),
    ]
