# Generated by Django 5.1.2 on 2024-10-28 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0007_student_task_department_id_student_task_school_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_task',
            old_name='department_id',
            new_name='department_ID',
        ),
        migrations.RenameField(
            model_name='student_task',
            old_name='school_id',
            new_name='school_ID',
        ),
    ]
