# Generated by Django 5.1.2 on 2024-10-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0008_teacher_task_perfomance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_task',
            name='roll_no',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
