# Generated by Django 5.1.2 on 2024-10-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0008_rename_department_id_student_task_department_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_task',
            name='active_on',
            field=models.BooleanField(default=True),
        ),
    ]
