# Generated by Django 5.1.2 on 2024-10-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_app', '0010_remove_department_task_school_id'),
        ('school_app', '0003_rename_active_on_school_task_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_task',
            name='department_ID',
            field=models.ManyToManyField(blank=True, to='department_app.department_task'),
        ),
    ]
