# Generated by Django 5.1.2 on 2024-11-14 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maching_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='matching',
            unique_together={('user1', 'user2')},
        ),
    ]
