# Generated by Django 5.1.2 on 2024-11-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maching_app', '0002_matching_score_alter_matching_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
