# Generated by Django 5.1.2 on 2024-11-19 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maching_app', '0003_alter_matching_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matching',
            unique_together=set(),
        ),
    ]
