# Generated by Django 5.1.2 on 2024-11-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_customuser_join_date_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subcription_plan',
            field=models.CharField(max_length=255),
        ),
    ]
