# Generated by Django 5.1.2 on 2024-11-22 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcription_app', '0001_initial'),
        ('user_app', '0005_customuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subcription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subcription_app.subcriptionforuser'),
        ),
    ]
