# Generated by Django 5.1.2 on 2024-11-27 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_app', '0004_profile_gallery_user_profile_table_profile_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_gallery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_gallery_set', to='user_profile_app.user_profile_table'),
        ),
        migrations.AlterField(
            model_name='user_profile_table',
            name='profile_gallery',
            field=models.ManyToManyField(blank=True, related_name='user_profiles_gallery', to='user_profile_app.profile_gallery'),
        ),
    ]
