# Generated by Django 5.1.2 on 2024-11-27 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_app', '0005_alter_profile_gallery_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile_table',
            name='profile_gallery',
        ),
        migrations.DeleteModel(
            name='Profile_Gallery',
        ),
    ]
